name: heart_game
description: A Flutter application for Heart Game with PHP backend

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_secure_storage: ^8.0.0
  image: ^4.0.17
  flutter_svg: ^2.0.7

  flutter_screenutil: ^5.9.3

  dio:
  supabase_flutter: ^2.9.1
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images
  #   - images/a_dot_ham.jpeg
